# Generated by Django 3.2.9 on 2021-11-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='craterusers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dj',
            options={},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='episodedj',
            options={},
        ),
        migrations.AlterModelOptions(
            name='episodegenre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parentgenre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='setlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AlterModelOptions(
            name='songartist',
            options={},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search_api.authuser')),
            ],
            options={
                'db_table': 'bookmark',
                'unique_together': {('bookmark_id', 'user')},
            },
        ),
    ]
